GET  http://localhost:3000/users/getAllUsers HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRF9VU1VBUklPIjoxLCJOT01FIjoiVml0b3IgRW1hbnVlbCBGbG9yZXMgUmVnaW5hdHRvIiwiSURfR1JVUE8iOjEsIkNFTFVMQVIiOiI1NS05OTczNTkzNTMiLCJJRF9DQVJHTyI6MSwiRk9UTyI6Imh0dHBzOi8vYXZhdGFycy5naXRodWJ1c2VyY29udGVudC5jb20vdS8zMzE1MjE5OD92PTQmc2l6ZT02NCIsIlNFTkhBX0NSSVBUT0dSQUZBREEiOiIkMmEkMTAkaVZMdjVhSGw0SWc2N29kemJady5HdXQ2REhmUDRteUVTcnlMelYzZFFyZ2lrT3VBdGRxUUsiLCJJRF9FTVBSRVNBIjoxLCJURUxFRk9ORSI6IjMzMzEtOTkyOCIsIkVNQUlMIjoidml0b3JfcmVnaW5hdHRvQGhvdG1haWwuY29tIiwiaWF0IjoxNzI3ODI1NTcwLCJleHAiOjE3Mjc4NDcxNzB9.EC_o9I08ipXyjKZkTjSfG3rpqFjnKOZhuEJ2K19x9UY

