POST http://localhost:3000/users/saveNewUser HTTP/1.1
content-type: application/json

{   "nome": "Alexandre Teste",
    "idGrupo": 1,
    "idCargo": 1,
    "foto": "https://avatars.githubusercontent.com/u/33152198?v=4&size=64",
    "senha": "vitor@15",
    "senhaConfirmacao": "vitor@15",
    "celular": "55-997359353",
    "idEmpresa": 1,
    "telefone": "3331-9928",
    "email": "xande_tonin@hotmail.com"
}