POST http://localhost:3000/users/update HTTP/1.1
content-type: application/json

{   
    "nome": "Mário Teste",
    "idGrupo": 1,
    "idCargo": 1,
    "foto": "https://avatars.githubusercontent.com/u/33152198?v=4&size=64",
    "celular": "55-333-9928",
    "idEmpresa": 1,
    "telefone": "3331-9928",
    "email": "mario@hotmail.com",
    "idUsuario" : 1
}
