GET http://localhost:3000/auth/getUserAuth HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiVml0b3IiLCJsYXN0TmFtZSI6IlJlZ2luYXR0byIsImVtYWlsIjoidml0b3JfcmVnaW5hdHRvQGhvdG1haWwuY29tIiwiaW1hZ2UiOiJodHRwczovL2F2YXRhcnMuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3UvMzMxNTIxOTg_dj00IiwiZ2VuZGVyIjoibWFsZSIsInBhc3N3b3JkIjoidml0b3JAMTUiLCJpYXQiOjE3Mjc4ODc1NjgsImV4cCI6MTcyNzkwOTE2OH0.41nMpocAW93Mh6jaaqNuQR1KrcPI0Gv5eIEpSEsoAdg

{
    
}